export const menuCategories = [
  { en: 'All', fr: 'Tout' },
  { en: 'Pizzas', fr: 'Pizzas' },
  { en: 'Pastas', fr: 'Pâtes' },
  { en: 'Salads', fr: 'Salades' },
  { en: 'Beverages', fr: 'Boissons' },
];

export const menuItems = [
  {
    id: 1,
    category: 'Pizzas',
    name: 'Margherita',
    description: 'Tomato sauce, mozzarella, basil',
    descriptionFr: 'Sauce tomate, mozzarella, basilic',
    price: 63,
  },
  {
    id: 2,
    category: 'Pizzas',
    name: 'Vegetariana',
    description: 'Mixed vegetables',
    descriptionFr: 'Légumes assortis',
    price: 78,
  },
  {
    id: 3,
    category: 'Pizzas',
    name: 'Pepperoni',
    description: 'Pepperoni, mozzarella',
    descriptionFr: 'Pepperoni, mozzarella',
    price: 105,
  },
  {
    id: 4,
    category: 'Pizzas',
    name: 'Quatro Fromaggi',
    description: 'Four cheeses',
    descriptionFr: 'Quatre fromages',
    price: 89,
  },
  {
    id: 5,
    category: 'Pizzas',
    name: 'Frutti Di Mare',
    description: 'Seafood',
    descriptionFr: 'Fruits de mer',
    price: 99,
  },
  {
    id: 6,
    category: 'Pizzas',
    name: 'Silvia Special',
    description: 'Specialty of the house',
    descriptionFr: 'Spécialité de la maison',
    price: 115,
  },
  {
    id: 7,
    category: 'Pizzas',
    name: 'Salmone',
    description: 'Salmon, cream cheese',
    descriptionFr: 'Saumon, fromage à la crème',
    price: 105,
  },
  {
    id: 8,
    category: 'Pizzas',
    name: 'Parma',
    description: 'Parma ham, rocket',
    descriptionFr: 'Jambon de Parme, roquette',
    price: 128,
  },
  {
    id: 9,
    category: 'Pastas',
    name: 'Spaghetti Bolognaise',
    description: 'Classic beef tomato sauce',
    descriptionFr: 'Sauce tomate classique au bœuf',
    price: 80,
  },
  {
    id: 10,
    category: 'Pastas',
    name: 'Penne Carbonara',
    description: 'Creamy egg sauce, pancetta',
    descriptionFr: 'Sauce crémeuse aux œufs, pancetta',
    price: 80,
  },
  {
    id: 11,
    category: 'Pastas',
    name: 'Lasagne Bolognaise',
    description: 'Layered pasta with rich ragù',
    descriptionFr: 'Pâtes en couches avec un riche ragù',
    price: 110,
  },
  {
    id: 12,
    category: 'Pastas',
    name: 'Spaghetti Frutti Di Mare',
    description: 'Mixed seafood, garlic, tomato',
    descriptionFr: 'Mélange de fruits de mer, ail, tomate',
    price: 110,
  },
  {
    id: 13,
    category: 'Salads',
    name: 'Salade César',
    description: 'Romaine, chicken, parmesan, croutons',
    descriptionFr: 'Romaine, poulet, parmesan, croûtons',
    price: 100,
  },
  {
    id: 14,
    category: 'Salads',
    name: 'Salade Italienne by Silvia',
    description: 'Tomato, mozzarella, basil, olives',
    descriptionFr: 'Tomate, mozzarella, basilic, olives',
    price: 110,
  },
  {
    id: 15,
    category: 'Salads',
    name: 'Salade Fruti De Mare',
    description: 'Seafood salad with citrus dressing',
    descriptionFr: 'Salade de fruits de mer avec vinaigrette aux agrumes',
    price: 78,
  },
  {
    id: 16,
    category: 'Beverages',
    name: 'Soft Drink',
    description: 'Fresh soda with ice',
    descriptionFr: 'Soda frais avec glace',
    price: 15,
  },
  {
    id: 17,
    category: 'Beverages',
    name: 'Fresh Juice',
    description: 'Orange or lemon juice',
    descriptionFr: 'Jus d\'orange ou de citron',
    price: 25,
  },
  {
    id: 18,
    category: 'Beverages',
    name: 'Sparkling Water',
    description: 'Chilled mineral water',
    descriptionFr: 'Eau minérale fraîche',
    price: 20,
  },
  {
    id: 19,
    category: 'Beverages',
    name: 'Italian Soda',
    description: 'House-made fruit soda',
    descriptionFr: 'Soda aux fruits fait maison',
    price: 30,
  },
];
