export const menuCategories = ['All', 'Pizzas', 'Pastas', 'Salads', 'Beverages'];

export const menuItems = [
  {
    id: 1,
    category: 'Pizzas',
    name: 'Margherita',
    description: 'Tomato sauce, mozzarella, basil',
    price: 63,
  },
  {
    id: 2,
    category: 'Pizzas',
    name: 'Vegetariana',
    description: 'Mixed vegetables',
    price: 78,
  },
  {
    id: 3,
    category: 'Pizzas',
    name: 'Pepperoni',
    description: 'Pepperoni, mozzarella',
    price: 105,
  },
  {
    id: 4,
    category: 'Pizzas',
    name: 'Quatro Fromaggi',
    description: 'Four cheeses',
    price: 89,
  },
  {
    id: 5,
    category: 'Pizzas',
    name: 'Frutti Di Mare',
    description: 'Seafood',
    price: 99,
  },
  {
    id: 6,
    category: 'Pizzas',
    name: 'Silvia Special',
    description: 'Specialty of the house',
    price: 115,
  },
  {
    id: 7,
    category: 'Pizzas',
    name: 'Salmone',
    description: 'Salmon, cream cheese',
    price: 105,
  },
  {
    id: 8,
    category: 'Pizzas',
    name: 'Parma',
    description: 'Parma ham, rocket',
    price: 128,
  },
  {
    id: 9,
    category: 'Pastas',
    name: 'Spaghetti Bolognaise',
    description: 'Classic beef tomato sauce',
    price: 80,
  },
  {
    id: 10,
    category: 'Pastas',
    name: 'Penne Carbonara',
    description: 'Creamy egg sauce, pancetta',
    price: 80,
  },
  {
    id: 11,
    category: 'Pastas',
    name: 'Lasagne Bolognaise',
    description: 'Layered pasta with rich ragù',
    price: 110,
  },
  {
    id: 12,
    category: 'Pastas',
    name: 'Spaghetti Frutti Di Mare',
    description: 'Mixed seafood, garlic, tomato',
    price: 110,
  },
  {
    id: 13,
    category: 'Salads',
    name: 'Salade César',
    description: 'Romaine, chicken, parmesan, croutons',
    price: 100,
  },
  {
    id: 14,
    category: 'Salads',
    name: 'Salade Italienne by Silvia',
    description: 'Tomato, mozzarella, basil, olives',
    price: 110,
  },
  {
    id: 15,
    category: 'Salads',
    name: 'Salade Fruti De Mare',
    description: 'Seafood salad with citrus dressing',
    price: 78,
  },
  {
    id: 16,
    category: 'Beverages',
    name: 'Soft Drink',
    description: 'Fresh soda with ice',
    price: 15,
  },
  {
    id: 17,
    category: 'Beverages',
    name: 'Fresh Juice',
    description: 'Orange or lemon juice',
    price: 25,
  },
  {
    id: 18,
    category: 'Beverages',
    name: 'Sparkling Water',
    description: 'Chilled mineral water',
    price: 20,
  },
  {
    id: 19,
    category: 'Beverages',
    name: 'Italian Soda',
    description: 'House-made fruit soda',
    price: 30,
  },
];
